[package]
name = "folder_hasher"
version = "0.1.0"
edition = "2021"

[dependencies]
humanize-bytes = "1.0.6"
indicatif = "0.17.9"
walkdir = "2"

[dependencies.xxhash-rust]
version = "0.8.12"
features = ["xxh3"]

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1